version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: korbit-report-api
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
