services:
    n8n-personal-searxng:
        image: searxng/searxng:latest
        container_name: n8n-personal-searxng
        networks:
          - nginx-proxy #같은 네트워크 이름을 적는다
        restart: unless-stopped
        ports:
          - 8888:8080
        environment:
          - SEARXNG_SECRET=n8n-personal-searxng-secret
          - SEARXNG_LIMITER=false
          - SEARXNG_BIND_ADDRESS=0.0.0.0
        volumes:
          - ./searxng:/etc/searxng
      
networks:           # 위의 networks랑 같게 네트워크 셋업을 해준다
  nginx-proxy:
    external: true
    name: nginx-proxy-manager_default